### ISSUE TITLE
invalid QRcode

### ISSUE THREAD

**Issue by oksanassss** [bcgov/vc-authn-oidc#135]
I connected to same network(http://test.bcovrin.vonx.io/genesis)  from vc-auth example and verify-email example. Verified email and added my mobile wallet. When ı tried to login with qr code ı have error invalid QRcode.

**Comment by esune** [comment]
How did you configure your proof-request? See [this comment](https://github.com/bcgov/vc-authn-oidc/issues/133#issuecomment-930303026) for tips on how to configure `vc-authn` to be used with Verified Email.

**Comment by oksanassss** [comment]
already ı used this.

**Comment by esune** [comment]
Can you please stop and restart the service? If you are using the free/unregistered version of ngrok the tunnel will expire after a while, causing the invalid QR code error.

**Comment by oznfc** [comment]
ı have same error.  I could run project first times , but now I have  ```invalid qr code ``` error. its my yaml file 
```
authtoken: "my-authtoken" 
tunnels:
  vc-authn-controller:
    addr: 5000
    proto: http
    bind-tls: true  

  vc-authn-agent:
    addr: 5679
    proto: http
    bind-tls: true
    ```
