### ISSUE TITLE
Chart releaser action does not detect changes unless they are in the latest commit

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#326]
The Helm chart releaser action seems to not be detecting changes to the chart files unless they are on the latest commit the action is being triggered by.

It is likely caused by this configuration:
```
steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
```

`fetch-depth` (see https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---depthltdepthgt) only checks-out the latest commit, which may not contain the changes to the chart. Removing the option, or using `unshallow`  (see https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---unshallow) might be the way to go.
