### ISSUE TITLE
ngrok now requires a free account and authtoken

### ISSUE THREAD

**Issue by russorat** [bcgov/vc-authn-oidc#402]
PM from ngrok here. I'm opening this issue to let you know what ngrok has recently started requiring a free account and authtoken to start the agent. It looks like your software already works with an authtoken, but there might be users or integrations or docs that need to updated.

Please reach out to support@ngrok.com if you are having any issues. 

Thanks again for using ngrok!

I've copied the original notice posted to twitter below:
```
As a part of our ongoing efforts to make ngrok more secure, starting on December 19, 2023, all usage of ngrok will require an account on either our free or paid tiers. 

To connect to the ngrok service via the agent, SDK, or ingress controller, you must add a valid authtoken that is linked to an active free or paid account. Any new or existing connections without a valid authtoken will result in error code 4018.

Learn more here: https://ngrok.com/docs/errors/err_ngrok_4018/
```

**Comment by esune** [comment]
To continue using the service with only one authtoken, some changes need to be implemented:
- update `docker-compose-ngrok.yaml` to only start one ngrok service:
```yaml
version: "3"
services:
  ngrok:
    image: ngrok/ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - 4046:4040
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
          - ./ngrok-dev.yml:/etc/ngrok.yml
    networks:
      - vc_auth

networks:
  vc_auth:
    driver: bridge
```
* create an `ngrok.yml` configurationf ile:
```yaml
version: 2
tunnels:
  controller-ngrok:
    addr: controller:${CONTROLLER_SERVICE_PORT}
    proto: http
    schemes:
      - https
  aca-py-ngrok:
    addr: aca-py:${AGENT_HTTP_PORT}
    proto: http
    schemes:
      - https
log: stdout
```
* update the `manage` script to create `ngrok-dev.yml` as a copy of `ngrok.yml`, with the service ports replaced with the desired targets (based on initialization script)
* update the `manage` script to determine the controller/agent ngrok URLs by querying the endpoints exposed by the new unique ngrok service
